# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

server:
  port: 8089

ecos:
  webapp:
    task:
      schedulers:
        ecos-patches:
          corePoolSize: 1

    dataSources:
      main:
        url: jdbc:postgresql://localhost:14523/ecos_apps
        username: apps
        password: appspassword
      main-xa-aware:
        url: jdbc:postgresql://localhost:14523/ecos_apps
        username: apps
        password: appspassword
    x509:
      keys:
        application:
          location: classpath:ecos/x509/keys/application.key

spring:
  boot:
    admin:
      context-path: '/admin'
      ui:
        brand: Citeck
      discovery:
        converter:
          management-context-path: '/management'

ecos-apps:
  modules-watcher:
    init-delay-ms: 10000
