modelVersion: "1.0"

name:
  ru: Конфигурация
  en: Config

source-id: "config"

controller:
  type: json
  config:
    idTemplate: ${scope|presuf('','$')}${id}
    attsValues:
      scope: "${scope!$appName{?str|presuf('app/')}}"
